server {
	listen 8080;
	server_name localhost;
	error_page 400 /error_pages/400.html;
	error_page 403 /error_pages/403.html;
	error_page 404 /error_pages/404.html;
	error_page 405 /error_pages/405.html;
	error_page 413 /error_pages/413.html;
	error_page 500 /error_pages/500.html;
	error_page 501 /error_pages/501.html;
	error_page 504 /error_pages/504.html;
	client_max_body_size 2M;

	location / {
		root ./www;
		index index.html index.htm;
		allowed_methods GET;
		autoindex off;
	}

	location /uploads {
		root .;
		allowed_methods GET POST DELETE;
		upload_path ./uploads;
		autoindex on;
	}

	location /inc {
		root ./includes/;
		allowed_methods GET POST DELETE;
		upload_path ./uploads;
		autoindex off;
	}

	location /cgi-bin/php {
		root .;
		allowed_methods GET POST;
		cgi_extension .php;
		cgi_path /usr/bin/php-cgi;
	}

	location /cgi-bin/py {
		root .;
		allowed_methods GET POST;
		cgi_extension .py;
		cgi_path /usr/bin/python3;
	}

}

